services:
  ameca:
    network_mode: bridge
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - LOG_LEVEL=ameca_pg=debug,info
     # - DISCORD_TOKEN=""
    #  - BOT_USER=""
    volumes:
      - /var/log/mempaste:/app/logs
    # Overrides default command so things don't shut down after the process ends.
    ports:
      - 4444:4444
