services:
  db:
    image: postgres
    container_name: ameca_pg_deploy
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ameca
    networks:
      - test_network
  ameca:
    container_name: ameca_bot
    networks:
      - test_network
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - LOG_LEVEL=ameca_pg=debug,info
     # - DISCORD_TOKEN=""
    #  - BOT_USER=""
    volumes:
      - /var/log/ameca:/app/logs
    # Overrides default command so things don't shut down after the process ends.
    ports:
      - 4444:4444
networks:
  test_network:
    driver: bridge